import { Component, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { OperationsLiveService } from '../../../core/services/operations-live.service';
import { RecipeMasterDataService } from '../../../core/services/recipe-master-data.service';

@Component({
  selector: 'app-production',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterLink],
  template: `
    <div class="max-w-md mx-auto min-h-full flex flex-col relative bg-background-light dark:bg-background-dark">
      <!-- Header -->
      <header class="bg-surface-light dark:bg-surface-dark px-6 pt-6 pb-4 shadow-sm sticky top-0 z-10">
        <div class="flex items-center justify-between mb-2">
          <div class="flex items-center space-x-2">
            <button class="text-text-sub-light dark:text-text-sub-dark hover:text-primary transition-colors">
              <span class="material-icons-round text-2xl">history</span>
            </button>
          </div>
        </div>
        <h1 class="text-2xl font-bold tracking-tight text-text-main-light dark:text-text-main-dark">New Production</h1>
        <p class="text-sm text-text-sub-light dark:text-text-sub-dark mt-1">Raw Material to Semifinished Goods</p>
      </header>

      <!-- Main Content -->
      <main class="flex-1 overflow-y-auto px-6 py-6 space-y-6 pb-32">
        <!-- Flavor + Batch Code -->
        <div class="bg-surface-light dark:bg-surface-dark p-5 rounded-2xl shadow-sm border border-border-light dark:border-border-dark space-y-5">
          <div>
            <label class="block text-sm font-medium text-text-sub-light dark:text-text-sub-dark mb-2">Flavor Profile</label>
            <div class="relative">
                <select [formControl]="form.controls.flavorId"
                      (change)="onFlavorChange()"
                      class="block w-full pl-4 pr-10 py-3 text-base border-border-light dark:border-border-dark focus:ring-primary focus:border-primary rounded-xl bg-gray-50 dark:bg-gray-800 text-text-main-light dark:text-text-main-dark appearance-none transition shadow-sm">
                <option value="">Select Flavor...</option>
                @for (f of flavors(); track f.id) {
                  <option [value]="f.id">{{ f.name }} ({{ f.code }})</option>
                }
              </select>
              <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-4 text-text-sub-light dark:text-text-sub-dark">
                <span class="material-icons-round">expand_more</span>
              </div>
            </div>
          </div>
          <div>
            <div class="flex justify-between items-center mb-2">
              <label class="block text-sm font-medium text-text-sub-light dark:text-text-sub-dark">Batch Code</label>
              <span class="text-xs bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300 px-2 py-0.5 rounded-full font-medium">Autogenerated</span>
            </div>
            <div class="flex items-center bg-gray-100 dark:bg-gray-900 border border-border-light dark:border-border-dark rounded-xl px-4 py-3">
              <span class="material-icons-round text-text-sub-light mr-3">qr_code_2</span>
              <span class="text-lg font-mono font-semibold tracking-wider text-text-main-light dark:text-text-main-dark">{{ batchCode() }}</span>
            </div>
          </div>
        </div>

        <!-- Recipe Ingredients -->
        <div class="space-y-3">
          <div class="flex items-center justify-between">
            <h2 class="text-lg font-semibold text-text-main-light dark:text-text-main-dark">Recipe Ingredients</h2>
            <a routerLink="../recipes" class="text-primary text-sm font-medium hover:text-primary-hover flex items-center">
              <span class="material-icons-round text-base mr-1">edit</span> Edit Recipe
            </a>
          </div>
          <div class="bg-surface-light dark:bg-surface-dark rounded-2xl shadow-sm border border-border-light dark:border-border-dark overflow-hidden">
            <!-- Table Header -->
            <div class="grid grid-cols-12 gap-2 bg-gray-50 dark:bg-gray-800/50 px-4 py-3 border-b border-border-light dark:border-border-dark text-xs font-semibold text-text-sub-light uppercase tracking-wider">
              <div class="col-span-7">Item</div>
              <div class="col-span-5 text-right">Qty (Kg)</div>
            </div>
            <!-- Rows -->
            <div class="divide-y divide-gray-100 dark:divide-gray-800">
              @if (recipeItems().length === 0) {
                <div class="px-4 py-4 text-sm text-text-sub-light dark:text-text-sub-dark">
                  No recipe is mapped to this flavor. Map a recipe in Admin Dashboard > Recipes.
                </div>
              }
              @for (item of recipeItems(); track item.ingredientId) {
                <div class="grid grid-cols-12 gap-2 px-4 py-3 items-center hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">
                  <div class="col-span-7 font-medium text-text-main-light dark:text-text-main-dark">{{ item.name }}</div>
                  <div class="col-span-5 text-right font-medium text-text-main-light dark:text-text-main-dark">
                    {{ item.qty.toFixed(2) }} {{ item.unit }}
                  </div>
                </div>
              }
            </div>
            <!-- Expected Yield -->
            <div class="grid grid-cols-12 gap-2 px-4 py-3 bg-blue-50 dark:bg-blue-900/10 border-t border-blue-100 dark:border-blue-900/30">
              <div class="col-span-7 font-bold text-primary">Expected Yield</div>
              <div class="col-span-5 text-right font-bold text-primary">{{ expectedYield().toFixed(1) }} kg</div>
            </div>
          </div>
        </div>

        <!-- Manufacturing Date + Actual Output -->
        <div class="bg-surface-light dark:bg-surface-dark p-5 rounded-2xl shadow-sm border border-border-light dark:border-border-dark space-y-5">
          <div>
            <label class="block text-sm font-medium text-text-sub-light dark:text-text-sub-dark mb-2">Manufacturing Date</label>
            <div class="relative">
              <input [formControl]="form.controls.mfgDate" type="date"
                     class="block w-full pl-10 pr-4 py-3 text-text-main-light dark:text-text-main-dark border-border-light dark:border-border-dark rounded-xl focus:ring-primary focus:border-primary bg-gray-50 dark:bg-gray-800 shadow-sm">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center px-3 text-text-sub-light dark:text-text-sub-dark">
                <span class="material-icons-round text-xl">event</span>
              </div>
            </div>
          </div>
          <div>
            <label class="block text-sm font-medium text-text-sub-light dark:text-text-sub-dark mb-2">Actual Production Output (Kg)</label>
            <div class="relative">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center px-4 text-text-sub-light dark:text-text-sub-dark">
                <span class="material-icons-round">scale</span>
              </div>
              <input [formControl]="form.controls.actualOutput" type="number" placeholder="0.00"
                     class="block w-full pl-12 pr-12 py-4 text-xl font-semibold text-text-main-light dark:text-text-main-dark border-border-light dark:border-border-dark rounded-xl focus:ring-primary focus:border-primary bg-gray-50 dark:bg-gray-800 shadow-sm">
              <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-4 text-text-sub-light font-medium">
                Kg
              </div>
            </div>
            <p class="mt-2 text-xs text-text-sub-light dark:text-text-sub-dark flex items-center">
              <span class="material-icons-round text-sm mr-1">info</span>
              System allows ±5% tolerance from expected yield.
            </p>
          </div>
        </div>

        @if (submitMessage()) {
          <div class="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800 dark:border-green-900/40 dark:bg-green-900/20 dark:text-green-300">
            {{ submitMessage() }}
          </div>
        }
      </main>

      <!-- Bottom Action Bar -->
      <div class="sticky bottom-0 left-0 right-0 p-6 bg-surface-light/90 dark:bg-surface-dark/90 backdrop-blur-md border-t border-border-light dark:border-border-dark z-20">
        <button (click)="onConfirm()"
                [disabled]="!selectedRecipe()"
                class="w-full bg-primary hover:bg-primary-hover text-white font-bold py-4 px-6 rounded-xl shadow-lg shadow-blue-500/30 transition-all active:scale-[0.98] flex items-center justify-center space-x-2">
          <span class="material-icons-round">check_circle</span>
          <span>Confirm & Save Production</span>
        </button>
      </div>
    </div>
  `,
})
export class ProductionComponent {
  private readonly fb = inject(FormBuilder);
  private readonly masterData = inject(RecipeMasterDataService);
  private readonly operations = inject(OperationsLiveService);

  readonly flavors = this.masterData.activeFlavors;

  form = this.fb.nonNullable.group({
    flavorId: ['', Validators.required],
    mfgDate: [new Date().toISOString().split('T')[0]],
    actualOutput: [0, [Validators.required, Validators.min(0.01)]],
  });

  batchCode = signal('--');
  submitMessage = signal('');

  readonly selectedRecipe = computed(() =>
    this.masterData.getRecipeForFlavor(this.form.controls.flavorId.value),
  );

  readonly recipeItems = computed(() =>
    this.masterData.resolveRecipeIngredients(this.selectedRecipe()),
  );

  expectedYield = computed(() => {
    return this.masterData.recipeYield(this.selectedRecipe());
  });

  onFlavorChange(): void {
    const flavorId = this.form.controls.flavorId.value;
    const flavor = this.flavors().find(f => f.id === flavorId);
    if (flavor) {
      const today = new Date();
      const dateStr = `${String(today.getDate()).padStart(2, '0')}${String(today.getMonth() + 1).padStart(2, '0')}${today.getFullYear()}`;
      this.batchCode.set(`${dateStr}-${flavor.code}-01`);
    } else {
      this.batchCode.set('--');
    }
  }

  async onConfirm(): Promise<void> {
    if (this.form.valid) {
      const flavor = this.flavors().find((item) => item.id === this.form.controls.flavorId.value);
      if (!this.selectedRecipe()) {
        this.submitMessage.set('This flavor is not mapped to any recipe. Configure mapping in Admin Dashboard > Recipes.');
        return;
      }

      const expectedYield = this.expectedYield();
      const actualOutput = Number(this.form.controls.actualOutput.value) || 0;

      try {
        const event = await this.operations.submitProduction({
          flavorName: flavor?.name ?? 'Unknown Flavor',
          batchCode: this.batchCode(),
          expectedYieldKg: expectedYield,
          actualOutputKg: actualOutput,
        });

        this.submitMessage.set(
          `Production logged by ${event.workerName}. Batch ${event.batchCode} synced to command center.`,
        );
        this.form.controls.actualOutput.setValue(0);
      } catch {
        this.submitMessage.set('Unable to submit production right now.');
      }
    }
  }
}
